vich_uploader:
    db_driver: orm

    mappings:
        logo:
            uri_prefix: /images/logo
            upload_destination: '%kernel.project_dir%/public/images/logo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer: App\Vich\LogoDirectoryNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        pictures:
            uri_prefix: /images/slider
            upload_destination: '%kernel.project_dir%/public/images/slider'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer: App\Vich\LogoDirectoryNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true