<?php

namespace App\DataFixtures;

use App\Entity\Activity;
use App\Entity\Services;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\String\Slugger\SluggerInterface;

class ActivityFixtures extends Fixture
{
    public function __construct(
        private readonly SluggerInterface $slugger
    ) {
    }

    public function load(ObjectManager $manager): void
    {
        $data = $this->getActivitiesWithServices();

        foreach ($data as $activityName => $services) {
            $activity = new Activity();
            $activity->setName($activityName);
            $activity->setSlug($this->slugify($activityName));
            $this->setReference('user_activity', $activity);
            $manager->persist($activity);

            foreach ($services as $serviceName) {
                $service = new Services();
                $service->setName($serviceName);
                $service->setActivity($activity);

                $manager->persist($service);
            }
        }

        $manager->flush();
    }

    private function slugify(string $text): string
    {
        return strtolower($this->slugger->slug($text)->toString());
    }

    private function getActivitiesWithServices(): array
    {
        return [
            'Maçon' => [
                'Construction de murs',
                'Rénovation façade',
                'Dallage béton',
                'Fondation maison',
                'Ouverture mur porteur',
                'Pose parpaings',
                'Enduit extérieur',
                'Chape béton',
                'Terrasse béton',
                'Extension maison',
            ],
            'Électricien' => [
                'Installation électrique',
                'Mise aux normes',
                'Dépannage électrique',
                'Pose tableau électrique',
                'Éclairage intérieur',
                'Éclairage extérieur',
                'Domotique',
                'Prise et interrupteur',
                'Chauffage électrique',
                'Câblage réseau',
            ],
            'Plombier' => [
                'Installation sanitaire',
                'Dépannage fuite',
                'Débouchage canalisation',
                'Installation chauffe-eau',
                'Rénovation salle de bain',
                'Pose robinetterie',
                'Installation WC',
                'Recherche fuite',
                'Chauffage plomberie',
                'Entretien chaudière',
            ],
            'Peintre' => [
                'Peinture intérieure',
                'Peinture extérieure',
                'Ravalement façade',
                'Pose papier peint',
                'Enduit décoratif',
                'Peinture plafond',
                'Peinture sol',
                'Traitement humidité',
                'Vernis bois',
                'Décoration murale',
            ],
            'Menuisier' => [
                'Fabrication meuble',
                'Pose cuisine',
                'Pose parquet',
                'Fabrication porte',
                'Fabrication fenêtre',
                'Escalier sur mesure',
                'Placard sur mesure',
                'Terrasse bois',
                'Rénovation bois',
                'Agencement intérieur',
            ],
            'Carreleur' => [
                'Pose carrelage',
                'Pose faïence',
                'Carrelage extérieur',
                'Pose mosaïque',
                'Rénovation sol',
                'Joint carrelage',
                'Étanchéité',
                'Carrelage salle de bain',
                'Terrasse carrelée',
                'Pose pierre',
            ],
            'Couvreur' => [
                'Pose toiture',
                'Réparation toiture',
                'Nettoyage toiture',
                'Isolation toiture',
                'Pose gouttières',
                'Étanchéité toit',
                'Pose tuiles',
                'Pose ardoises',
                'Démoussage',
                'Inspection toiture',
            ],
            'Chauffagiste' => [
                'Installation chauffage',
                'Entretien chaudière',
                'Dépannage chauffage',
                'Installation pompe à chaleur',
                'Radiateurs',
                'Chauffage au sol',
                'Réglage système',
                'Audit énergétique',
                'Remplacement chaudière',
                'Maintenance',
            ],
            'Serrurier' => [
                'Ouverture porte',
                'Changement serrure',
                'Blindage porte',
                'Installation serrure',
                'Dépannage urgence',
                'Pose verrou',
                'Sécurisation logement',
                'Clé perdue',
                'Coffre-fort',
                'Maintenance serrurerie',
            ],
            'Vitrier' => [
                'Pose vitrage',
                'Remplacement vitre',
                'Double vitrage',
                'Vitrine magasin',
                'Dépannage casse',
                'Miroir sur mesure',
                'Isolation vitrage',
                'Film protection',
                'Réparation fenêtre',
                'Pose baie vitrée',
            ],
            'Développeur web' => [
                'Création site vitrine',
                'Création site e-commerce',
                'Développement Symfony',
                'Développement API',
                'Maintenance site',
                'Correction de bugs',
                'Optimisation performance',
                'Intégration HTML CSS',
                'Refonte site web',
                'Sécurité application',
            ],
            'Web designer' => [
                'Maquette UI',
                'UX design',
                'Design mobile',
                'Refonte graphique',
                'Charte graphique',
                'Wireframe',
                'Prototype Figma',
                'Landing page design',
                'Design e-commerce',
                'Bannières web',
            ],
            'Consultant SEO' => [
                'Audit SEO',
                'SEO technique',
                'Recherche mots-clés',
                'Optimisation contenu',
                'Netlinking',
                'SEO local',
                'Analyse concurrentielle',
                'Optimisation vitesse',
                'Suivi positionnement',
                'Stratégie SEO',
            ],
            'Community manager' => [
                'Gestion Facebook',
                'Gestion Instagram',
                'Gestion TikTok',
                'Création visuels',
                'Calendrier éditorial',
                'Modération commentaires',
                'Réponse messages',
                'Publicité social media',
                'Analyse statistiques',
                'Stratégie contenu',
            ],
            'Rédacteur web' => [
                'Article de blog',
                'Rédaction SEO',
                'Fiche produit',
                'Page de vente',
                'Newsletter',
                'Relecture',
                'Réécriture contenu',
                'Description service',
                'Script vidéo',
                'Contenu réseaux sociaux',
            ],
            'Coiffeur' => [
                'Coupe homme',
                'Coupe femme',
                'Coloration',
                'Brushing',
                'Lissage',
                'Permanente',
                'Coiffure mariage',
                'Barbe',
                'Soin cheveux',
                'Coupe enfant',
            ],
            'Esthéticienne' => [
                'Soin visage',
                'Épilation',
                'Manucure',
                'Pédicure',
                'Maquillage',
                'Soin corps',
                'Gommage',
                'Extension cils',
                'Beauté mains',
                'Massage esthétique',
            ],
            'Mécanicien auto' => [
                'Vidange',
                'Révision complète',
                'Freinage',
                'Diagnostic panne',
                'Remplacement batterie',
                'Entretien pneus',
                'Réparation moteur',
                'Embrayage',
                'Pré-contrôle technique',
                'Climatisation auto',
            ],
            'Jardinier' => [
                'Tonte pelouse',
                'Taille haies',
                'Entretien jardin',
                'Plantation',
                'Élagage',
                'Désherbage',
                'Création massif',
                'Arrosage automatique',
                'Nettoyage extérieur',
                'Aménagement paysager',
            ],
            'Femme de ménage' => [
                'Nettoyage maison',
                'Grand ménage',
                'Repassage',
                'Nettoyage vitres',
                'Nettoyage cuisine',
                'Nettoyage salle de bain',
                'Désinfection',
                'Entretien bureau',
                'Ménage après travaux',
                'Entretien régulier',
            ],
            'Agent immobilier' => [
                'Estimation bien',
                'Visite appartement',
                'Mise en vente',
                'Mise en location',
                'Conseil investissement',
                'Gestion locative',
                'Photographie immobilière',
                'Rédaction annonce',
                'Accompagnement achat',
                'Négociation immobilière',
            ],
            'Architecte' => [
                'Plan maison',
                'Permis de construire',
                'Extension habitation',
                'Rénovation architecturale',
                'Aménagement intérieur',
                'Suivi chantier',
                'Étude faisabilité',
                'Modélisation 3D',
                'Maison contemporaine',
                'Conseil architecture',
            ],
            'Décorateur intérieur' => [
                'Conseil décoration',
                'Aménagement salon',
                'Aménagement chambre',
                'Choix couleurs',
                'Sélection mobilier',
                'Home staging',
                'Décoration bureau',
                'Ambiance lumineuse',
                'Décoration haut de gamme',
                'Shopping déco',
            ],
            'Frigoriste' => [
                'Installation climatisation',
                'Entretien climatisation',
                'Dépannage clim',
                'Pose chambre froide',
                'Maintenance frigorifique',
                'Recharge gaz',
                'Réparation pompe à chaleur',
                'Réglage température',
                'Audit installation',
                'Remplacement équipement',
            ],
            'Façadier' => [
                'Ravalement façade',
                'Nettoyage façade',
                'Enduit façade',
                'Isolation extérieure',
                'Peinture façade',
                'Réparation fissures',
                'Hydrofuge façade',
                'Traitement humidité',
                'Façade maison',
                'Façade immeuble',
            ],
            'Staffeur' => [
                'Pose corniches',
                'Rosaces plafond',
                'Moulures murales',
                'Création staff',
                'Restauration ornements',
                'Décoration plafond',
                'Habillage cheminée',
                'Faux plafond décoratif',
                'Colonnes décoratives',
                'Finitions staff',
            ],
            'Plaquiste' => [
                'Pose placo',
                'Création cloisons',
                'Faux plafond',
                'Doublage murs',
                'Isolation intérieure',
                'Aménagement combles',
                'Bande à joint',
                'Cloison acoustique',
                'Cloison hydrofuge',
                'Habillage technique',
            ],
            'Solier moquettiste' => [
                'Pose moquette',
                'Pose PVC',
                'Pose lino',
                'Pose sol souple',
                'Rénovation revêtement',
                'Préparation sol',
                'Pose plinthes',
                'Sol bureau',
                'Sol commercial',
                'Réparation revêtement',
            ],
            'Parqueteur' => [
                'Pose parquet massif',
                'Pose parquet stratifié',
                'Pose parquet flottant',
                'Ponçage parquet',
                'Vitrification parquet',
                'Réparation parquet',
                'Parquet huilé',
                'Parquet collé',
                'Parquet terrasse',
                'Entretien parquet',
            ],
            'Pisciniste' => [
                'Construction piscine',
                'Entretien piscine',
                'Réparation liner',
                'Pose pompe piscine',
                'Traitement eau',
                'Pose abri piscine',
                'Hivernage piscine',
                'Nettoyage bassin',
                'Rénovation piscine',
                'Sécurité piscine',
            ],
            'Terrassier' => [
                'Terrassement maison',
                'Nivellement terrain',
                'Tranchée technique',
                'Préparation fondations',
                'Évacuation gravats',
                'Raccordement extérieur',
                'Drainage terrain',
                'Chemin d’accès',
                'Enrochement',
                'Aménagement terrain',
            ],
            'Conducteur de travaux' => [
                'Suivi chantier',
                'Planification travaux',
                'Coordination artisans',
                'Contrôle qualité',
                'Gestion budget chantier',
                'Réunion chantier',
                'Reporting travaux',
                'Contrôle sécurité',
                'Réception chantier',
                'Pilotage projet',
            ],
            'Ferronnier' => [
                'Portail sur mesure',
                'Garde-corps métal',
                'Escalier métal',
                'Marquise',
                'Clôture fer forgé',
                'Mobilier métallique',
                'Pergola métal',
                'Restauration ferronnerie',
                'Soudure décorative',
                'Protection fenêtre',
            ],
            'Soudeur' => [
                'Soudure acier',
                'Soudure inox',
                'Soudure aluminium',
                'Assemblage métallique',
                'Réparation châssis',
                'Soudure portail',
                'Soudure garde-corps',
                'Fabrication structure',
                'Renfort métallique',
                'Découpe métal',
            ],
            'Charpentier' => [
                'Charpente bois',
                'Rénovation charpente',
                'Extension ossature bois',
                'Pose poutres',
                'Traitement bois',
                'Abri bois',
                'Pergola bois',
                'Surélévation maison',
                'Inspection charpente',
                'Réparation structure',
            ],
            'Storiste' => [
                'Pose store banne',
                'Pose volet roulant',
                'Motorisation store',
                'Réparation store',
                'Réparation volet',
                'Store intérieur',
                'Store extérieur',
                'Moustiquaire',
                'Pergola bioclimatique',
                'Entretien installation',
            ],
            'Cordiste' => [
                'Travaux en hauteur',
                'Nettoyage vitres hauteur',
                'Purge façade',
                'Inspection toiture',
                'Pose ligne de vie',
                'Maintenance bâtiment',
                'Sécurisation hauteur',
                'Travaux accès difficile',
                'Réparation façade hauteur',
                'Pose filet sécurité',
            ],
            'Dératiseur' => [
                'Traitement rats',
                'Traitement souris',
                'Traitement cafards',
                'Désinsectisation',
                'Désinfection locaux',
                'Lutte punaises de lit',
                'Traitement guêpes',
                'Traitement frelons',
                'Prévention nuisibles',
                'Contrat entretien nuisibles',
            ],
            'Ramoneur' => [
                'Ramonnage cheminée',
                'Ramonnage poêle',
                'Entretien conduit',
                'Débistrage',
                'Contrôle fumisterie',
                'Nettoyage conduit',
                'Intervention sécurité',
                'Certificat ramonage',
                'Ramonage chaudière',
                'Inspection conduit',
            ],
            'Déménageur' => [
                'Déménagement local',
                'Déménagement national',
                'Emballage mobilier',
                'Montage meubles',
                'Démontage meubles',
                'Transport objets lourds',
                'Location monte-meuble',
                'Stockage temporaire',
                'Déménagement entreprise',
                'Protection mobilier',
            ],
            'Serrurier métallier' => [
                'Fabrication portail',
                'Pose garde-corps',
                'Blindage sur mesure',
                'Création structure métal',
                'Escalier acier',
                'Portillon métallique',
                'Clôture acier',
                'Réparation métallique',
                'Renforcement sécurité',
                'Pose grille défense',
            ],
            'Tailleur de pierre' => [
                'Taille pierre',
                'Restauration façade pierre',
                'Cheminée pierre',
                'Escalier pierre',
                'Encadrement fenêtre',
                'Muret pierre',
                'Dallage pierre',
                'Sculpture pierre',
                'Parement pierre',
                'Réparation monument',
            ],
            'Tapissier' => [
                'Réfection fauteuil',
                'Réfection canapé',
                'Pose tissu mural',
                'Rideaux sur mesure',
                'Tête de lit',
                'Garnissage siège',
                'Décoration textile',
                'Habillage mobilier',
                'Coussins sur mesure',
                'Restauration assise',
            ],
            'Photographe' => [
                'Portrait professionnel',
                'Photographie mariage',
                'Photographie produit',
                'Photographie immobilière',
                'Retouche photo',
                'Photographie événement',
                'Book photo',
                'Shooting entreprise',
                'Photo culinaire',
                'Photo réseaux sociaux',
            ],
            'Vidéaste' => [
                'Vidéo promotionnelle',
                'Montage vidéo',
                'Captation événement',
                'Interview vidéo',
                'Vidéo drone',
                'Réalisation clip',
                'Motion design simple',
                'Vidéo réseaux sociaux',
                'Teaser entreprise',
                'Sous-titrage vidéo',
            ],
            'Monteur vidéo' => [
                'Montage YouTube',
                'Montage TikTok',
                'Montage publicitaire',
                'Ajout sous-titres',
                'Habillage vidéo',
                'Découpe séquences',
                'Correction audio',
                'Optimisation format',
                'Export multi-plateforme',
                'Miniature vidéo',
            ],
            'Graphiste' => [
                'Logo',
                'Carte de visite',
                'Flyer',
                'Brochure',
                'Affiche',
                'Bannière publicitaire',
                'Identité visuelle',
                'Visuel réseaux sociaux',
                'Catalogue',
                'Retouche graphique',
            ],
            'Imprimeur' => [
                'Impression flyers',
                'Impression affiches',
                'Impression cartes visite',
                'Impression brochures',
                'Impression catalogues',
                'Signalétique',
                'Impression autocollants',
                'Impression bâches',
                'Papeterie entreprise',
                'Finition impression',
            ],
            'Traducteur' => [
                'Traduction français anglais',
                'Traduction anglais français',
                'Traduction site web',
                'Traduction documents',
                'Relecture bilingue',
                'Traduction commerciale',
                'Traduction juridique',
                'Sous-titrage traduction',
                'Localisation contenu',
                'Correction linguistique',
            ],
            'Interprète' => [
                'Interprétation rendez-vous',
                'Interprétation conférence',
                'Interprétation téléphonique',
                'Accompagnement administratif',
                'Interprétation commerciale',
                'Traduction orale',
                'Interprétation consécutive',
                'Interprétation liaison',
                'Accompagnement médical',
                'Interprétation juridique',
            ],
            'Formateur informatique' => [
                'Formation Word',
                'Formation Excel',
                'Formation PowerPoint',
                'Formation internet',
                'Formation bureautique',
                'Formation cybersécurité',
                'Formation débutant',
                'Formation entreprise',
                'Atelier pratique',
                'Support de cours',
            ],
            'Consultant marketing' => [
                'Stratégie marketing',
                'Audit marketing',
                'Positionnement marque',
                'Tunnel de vente',
                'Campagne acquisition',
                'Analyse concurrence',
                'Plan marketing',
                'Email marketing',
                'Conseil conversion',
                'Suivi KPI',
            ],
            'Consultant en communication' => [
                'Stratégie communication',
                'Communication entreprise',
                'Plan média',
                'Communication digitale',
                'Message de marque',
                'Communication de crise',
                'Relations presse',
                'Prise de parole',
                'Audit communication',
                'Conseil image',
            ],
            'Assistant administratif' => [
                'Saisie de données',
                'Gestion documents',
                'Classement dossiers',
                'Traitement mails',
                'Devis et factures',
                'Prise de rendez-vous',
                'Relance clients',
                'Secrétariat externalisé',
                'Mise en page documents',
                'Support administratif',
            ],
            'Comptable' => [
                'Saisie comptable',
                'Déclaration TVA',
                'Bilan comptable',
                'Compte de résultat',
                'Suivi trésorerie',
                'Facturation',
                'Relance impayés',
                'Conseil fiscal de base',
                'Gestion charges',
                'Révision comptable',
            ],
            'Expert-comptable' => [
                'Bilan annuel',
                'Liasse fiscale',
                'Création société',
                'Conseil fiscal',
                'Prévisionnel',
                'Tableau de bord',
                'Audit financier',
                'Paie et social',
                'Optimisation gestion',
                'Accompagnement dirigeant',
            ],
            'Juriste' => [
                'Rédaction contrat',
                'Analyse contrat',
                'Conseil juridique',
                'Mise en demeure',
                'Conditions générales',
                'Litige commercial',
                'Documentation légale',
                'Protection activité',
                'Veille réglementaire',
                'Conformité de base',
            ],
            'Avocat' => [
                'Conseil juridique',
                'Rédaction acte',
                'Défense contentieux',
                'Droit immobilier',
                'Droit commercial',
                'Droit du travail',
                'Consultation avocat',
                'Négociation litige',
                'Procédure judiciaire',
                'Recouvrement créance',
            ],
            'Courtier en assurance' => [
                'Assurance habitation',
                'Assurance auto',
                'Assurance santé',
                'Assurance professionnelle',
                'Comparaison contrats',
                'Optimisation garanties',
                'Accompagnement sinistre',
                'Assurance emprunteur',
                'Prévoyance',
                'Responsabilité civile',
            ],
            'Courtier en prêt' => [
                'Simulation prêt immobilier',
                'Recherche financement',
                'Renégociation crédit',
                'Rachat de crédit',
                'Montage dossier',
                'Comparaison banques',
                'Prêt professionnel',
                'Prêt travaux',
                'Conseil taux',
                'Accompagnement notaire',
            ],
            'Diagnostiqueur immobilier' => [
                'Diagnostic DPE',
                'Diagnostic amiante',
                'Diagnostic plomb',
                'Diagnostic gaz',
                'Diagnostic électricité',
                'Mesurage loi Carrez',
                'ERP',
                'Diagnostic termites',
                'Audit avant vente',
                'Rapport technique',
            ],
            'Notaire' => [
                'Acte de vente',
                'Compromis de vente',
                'Donation',
                'Succession',
                'Conseil immobilier',
                'Acte authentique',
                'Vérification titres',
                'Accompagnement acquisition',
                'Formalités notariales',
                'Consultation notariale',
            ],
            'Coach sportif' => [
                'Coaching perte de poids',
                'Renforcement musculaire',
                'Remise en forme',
                'Coaching à domicile',
                'Programme personnalisé',
                'Stretching',
                'Préparation physique',
                'Cardio training',
                'Suivi nutritionnel simple',
                'Coaching en ligne',
            ],
            'Professeur de yoga' => [
                'Cours de yoga débutant',
                'Yoga avancé',
                'Yoga à domicile',
                'Séance relaxation',
                'Respiration',
                'Yoga entreprise',
                'Yoga en ligne',
                'Stretching doux',
                'Méditation guidée',
                'Yoga prénatal',
            ],
            'Nutritionniste' => [
                'Bilan nutritionnel',
                'Programme alimentaire',
                'Perte de poids',
                'Prise de masse',
                'Rééquilibrage alimentaire',
                'Suivi nutritionnel',
                'Conseil repas',
                'Nutrition sportive',
                'Accompagnement motivation',
                'Plan nutritionnel',
            ],
            'Psychologue' => [
                'Consultation individuelle',
                'Gestion du stress',
                'Soutien émotionnel',
                'Confiance en soi',
                'Écoute active',
                'Suivi régulier',
                'Accompagnement burn-out',
                'Thérapie brève',
                'Consultation ado',
                'Consultation couple',
            ],
            'Baby-sitter' => [
                'Garde enfant soirée',
                'Garde après école',
                'Aide devoirs',
                'Jeux éducatifs',
                'Préparation repas enfant',
                'Sortie école',
                'Garde week-end',
                'Garde vacances',
                'Routine coucher',
                'Surveillance à domicile',
            ],
            'Auxiliaire de vie' => [
                'Aide au lever',
                'Aide au coucher',
                'Préparation repas',
                'Aide toilette',
                'Compagnie',
                'Courses à domicile',
                'Entretien logement léger',
                'Aide administrative',
                'Accompagnement rendez-vous',
                'Soutien quotidien',
            ],
            'Pet sitter' => [
                'Garde chien',
                'Garde chat',
                'Promenade chien',
                'Visite à domicile',
                'Nourrissage animaux',
                'Nettoyage litière',
                'Garde week-end',
                'Garde vacances',
                'Administration traitement simple',
                'Compagnie animale',
            ],
            'Toiletteur canin' => [
                'Bain chien',
                'Coupe canine',
                'Démêlage poils',
                'Coupe griffes',
                'Nettoyage oreilles',
                'Shampoing adapté',
                'Toilettage complet',
                'Entretien pelage',
                'Toilettage chat',
                'Soin esthétique animal',
            ],
            'Cuisinier à domicile' => [
                'Repas à domicile',
                'Batch cooking',
                'Menu personnalisé',
                'Cuisine familiale',
                'Repas événement',
                'Cuisine gastronomique',
                'Préparation dessert',
                'Repas sain',
                'Cuisine du monde',
                'Service à table',
            ],
            'Traiteur' => [
                'Buffet froid',
                'Buffet chaud',
                'Cocktail entreprise',
                'Mariage',
                'Anniversaire',
                'Repas séminaire',
                'Pièces cocktail',
                'Desserts événement',
                'Livraison repas',
                'Menu sur mesure',
            ],
            'Pâtissier' => [
                'Gâteau anniversaire',
                'Wedding cake',
                'Pièces montées',
                'Pâtisserie fine',
                'Desserts sur commande',
                'Tarte artisanale',
                'Entremets',
                'Macarons',
                'Buffet sucré',
                'Personnalisation gâteau',
            ],
            'Boulanger' => [
                'Pain artisanal',
                'Viennoiseries',
                'Pain complet',
                'Pain sans gluten',
                'Pain sandwich',
                'Fournée spéciale',
                'Livraison boulangerie',
                'Pain événement',
                'Baguette tradition',
                'Produits du matin',
            ],
            'Chauffeur VTC' => [
                'Transfert aéroport',
                'Trajet gare',
                'Déplacement business',
                'Transport privé',
                'Mise à disposition',
                'Trajet longue distance',
                'Transport événement',
                'Service premium',
                'Transport nuit',
                'Accueil personnalisé',
            ],
            'Livreur' => [
                'Livraison colis',
                'Livraison express',
                'Livraison repas',
                'Livraison documents',
                'Tournée locale',
                'Remise en main propre',
                'Livraison fragile',
                'Livraison commerce',
                'Collecte colis',
                'Transport léger',
            ],
            'Agent de sécurité' => [
                'Surveillance site',
                'Surveillance événement',
                'Contrôle accès',
                'Ronde sécurité',
                'Gardiennage',
                'Sécurité magasin',
                'Intervention préventive',
                'Filtrage entrée',
                'Sécurité incendie de base',
                'Protection locaux',
            ],
            'Magicien' => [
                'Animation anniversaire',
                'Spectacle enfants',
                'Magie close-up',
                'Animation mariage',
                'Animation entreprise',
                'Spectacle scène',
                'Tours personnalisés',
                'Animation cocktail',
                'Magie familiale',
                'Prestation événement',
            ],
            'DJ' => [
                'Animation mariage',
                'Animation anniversaire',
                'Soirée entreprise',
                'Mix personnalisé',
                'Playlist sur mesure',
                'Sonorisation',
                'Éclairage soirée',
                'Animation micro',
                'Prestation cocktail',
                'After party',
            ],
            'Musicien' => [
                'Concert privé',
                'Animation mariage',
                'Piano événement',
                'Guitare live',
                'Chant acoustique',
                'Ambiance cocktail',
                'Prestation restaurant',
                'Musique entreprise',
                'Répertoire personnalisé',
                'Duo musical',
            ],
            'Chanteur' => [
                'Chant mariage',
                'Animation privée',
                'Concert événement',
                'Reprise musicale',
                'Performance live',
                'Chant cérémonie',
                'Ambiance lounge',
                'Animation cocktail',
                'Set personnalisé',
                'Prestation acoustique',
            ],
            'Organisateur événementiel' => [
                'Organisation mariage',
                'Organisation anniversaire',
                'Organisation séminaire',
                'Coordination prestataires',
                'Décoration événement',
                'Gestion planning',
                'Recherche lieu',
                'Animation événement',
                'Suivi budget',
                'Organisation lancement',
            ],
            'Wedding planner' => [
                'Organisation mariage complète',
                'Coordination jour J',
                'Recherche prestataires',
                'Décoration mariage',
                'Planning mariage',
                'Gestion budget mariage',
                'Cérémonie laïque',
                'Mise en scène réception',
                'Accompagnement couple',
                'Organisation brunch',
            ],
            'Agent de nettoyage industriel' => [
                'Nettoyage entrepôt',
                'Nettoyage usine',
                'Nettoyage bureaux',
                'Décapage sol',
                'Nettoyage vitrerie',
                'Désinfection locaux',
                'Nettoyage fin chantier',
                'Entretien régulier',
                'Sortie poubelles',
                'Nettoyage haute pression',
            ],
            'Laveur de vitres' => [
                'Nettoyage vitres maison',
                'Nettoyage vitres bureaux',
                'Nettoyage baies vitrées',
                'Nettoyage véranda',
                'Nettoyage vitrines',
                'Nettoyage hauteur',
                'Entretien régulier vitres',
                'Décrassage vitres',
                'Nettoyage après travaux',
                'Vitrerie commerciale',
            ],
            'Réparateur électroménager' => [
                'Réparation lave-linge',
                'Réparation lave-vaisselle',
                'Réparation four',
                'Réparation réfrigérateur',
                'Réparation congélateur',
                'Diagnostic panne appareil',
                'Entretien électroménager',
                'Remplacement pièces',
                'Installation appareil',
                'Dépannage à domicile',
            ],
            'Informaticien' => [
                'Dépannage ordinateur',
                'Installation logiciel',
                'Suppression virus',
                'Sauvegarde données',
                'Réparation PC',
                'Réparation imprimante',
                'Installation réseau',
                'Maintenance informatique',
                'Montage PC',
                'Assistance à domicile',
            ],
            'Technicien réseau' => [
                'Installation réseau',
                'Configuration routeur',
                'Câblage informatique',
                'Wi-Fi entreprise',
                'Sécurisation réseau',
                'Maintenance réseau',
                'Baie de brassage',
                'Diagnostic connexion',
                'Supervision réseau',
                'Support technique',
            ],
            'Technicien domotique' => [
                'Installation domotique',
                'Maison connectée',
                'Éclairage connecté',
                'Volets connectés',
                'Alarme connectée',
                'Caméra connectée',
                'Scénarios automatisés',
                'Pilotage chauffage',
                'Maintenance domotique',
                'Configuration application',
            ],
            'Installateur alarme' => [
                'Pose alarme maison',
                'Pose alarme commerce',
                'Caméra surveillance',
                'Détecteur mouvement',
                'Contrôle accès',
                'Maintenance alarme',
                'Diagnostic sécurité',
                'Vidéosurveillance',
                'Système anti-intrusion',
                'Paramétrage alarme',
            ],
            'Installateur panneaux solaires' => [
                'Pose panneaux solaires',
                'Étude photovoltaïque',
                'Maintenance solaire',
                'Nettoyage panneaux',
                'Onduleur solaire',
                'Autoconsommation',
                'Raccordement installation',
                'Audit rentabilité',
                'Batterie solaire',
                'Installation résidentielle',
            ],
            'Ébéniste' => [
                'Meuble sur mesure',
                'Restauration meuble ancien',
                'Bibliothèque sur mesure',
                'Dressing sur mesure',
                'Table bois massif',
                'Agencement bois',
                'Finition bois',
                'Placage bois',
                'Mobilier haut de gamme',
                'Réparation mobilier',
            ],
            'Horloger' => [
                'Réparation montre',
                'Changement pile',
                'Réglage bracelet',
                'Entretien mécanisme',
                'Nettoyage montre',
                'Restauration horlogère',
                'Réglage pendule',
                'Polissage montre',
                'Diagnostic horloger',
                'Petite réparation',
            ],
            'Bijoutier' => [
                'Création bijou',
                'Réparation bijou',
                'Mise à taille bague',
                'Nettoyage bijou',
                'Polissage bijou',
                'Sertissage pierre',
                'Transformation bijou',
                'Bijou sur mesure',
                'Entretien joaillerie',
                'Gravure bijou',
            ],
            'Cordonnier' => [
                'Réparation chaussures',
                'Pose semelles',
                'Changement talons',
                'Entretien cuir',
                'Réparation sac',
                'Réparation ceinture',
                'Cirage chaussures',
                'Clés minute',
                'Petite maroquinerie',
                'Rénovation cuir',
            ],
            'Tatoueur' => [
                'Tatouage personnalisé',
                'Retouche tatouage',
                'Tatouage minimaliste',
                'Tatouage noir et gris',
                'Tatouage couleur',
                'Consultation projet',
                'Cover tatouage',
                'Petit tatouage',
                'Grand tatouage',
                'Conseil entretien tatouage',
            ],
            'Pierceur' => [
                'Piercing oreille',
                'Piercing nez',
                'Piercing nombril',
                'Piercing arcade',
                'Piercing lèvre',
                'Conseil bijou',
                'Remplacement bijou',
                'Suivi cicatrisation',
                'Hygiène piercing',
                'Piercing personnalisé',
            ],
            'Professeur particulier' => [
                'Cours mathématiques',
                'Cours français',
                'Cours anglais',
                'Aide aux devoirs',
                'Préparation examen',
                'Cours primaire',
                'Cours collège',
                'Cours lycée',
                'Cours à domicile',
                'Cours en ligne',
            ],
            'Professeur de musique' => [
                'Cours piano',
                'Cours guitare',
                'Cours chant',
                'Cours batterie',
                'Solfège',
                'Cours débutant',
                'Cours avancé',
                'Préparation audition',
                'Cours enfant',
                'Cours adulte',
            ],
            'Coach professionnel' => [
                'Coaching carrière',
                'Préparation entretien',
                'Confiance professionnelle',
                'Prise de parole',
                'Organisation travail',
                'Accompagnement transition',
                'Coaching entrepreneur',
                'Développement leadership',
                'Gestion stress pro',
                'Plan d’action',
            ],
            'Consultant RH' => [
                'Recrutement',
                'Fiche de poste',
                'Entretien candidat',
                'Onboarding',
                'Conseil RH',
                'Organisation interne',
                'Gestion compétences',
                'Audit RH',
                'Formation équipe',
                'Procédures RH',
            ],
            'Recruteur' => [
                'Sourcing candidats',
                'Tri CV',
                'Entretiens',
                'Publication annonces',
                'Approche directe',
                'Évaluation profil',
                'Recrutement cadre',
                'Recrutement terrain',
                'Compte-rendu recrutement',
                'Suivi intégration',
            ],
            'Téléprospecteur' => [
                'Prospection téléphonique',
                'Prise de rendez-vous',
                'Qualification leads',
                'Relance commerciale',
                'Suivi prospects',
                'Script d’appel',
                'Détection besoins',
                'Mise à jour CRM',
                'Prospection B2B',
                'Campagne sortante',
            ],
            'Commercial terrain' => [
                'Prospection terrain',
                'Rendez-vous client',
                'Présentation offre',
                'Négociation commerciale',
                'Suivi portefeuille',
                'Relance devis',
                'Closing vente',
                'Développement secteur',
                'Animation réseau',
                'Reporting commercial',
            ],
            'Agent de voyage' => [
                'Réservation vol',
                'Réservation hôtel',
                'Séjour sur mesure',
                'Voyage d’affaires',
                'Circuit touristique',
                'Conseil destination',
                'Formalités voyage',
                'Assurance voyage',
                'Voyage groupe',
                'Organisation séjour',
            ],
            'Guide touristique' => [
                'Visite guidée ville',
                'Visite patrimoine',
                'Circuit culturel',
                'Accompagnement groupe',
                'Guide privé',
                'Excursion journée',
                'Visite historique',
                'Guide multilingue',
                'Balade découverte',
                'Animation touristique',
            ],
            'Artisan maroquinier' => [
                'Sac sur mesure',
                'Réparation sac cuir',
                'Ceinture cuir',
                'Portefeuille sur mesure',
                'Entretien cuir',
                'Création petite maroquinerie',
                'Personnalisation cuir',
                'Restauration cuir',
                'Étui cuir',
                'Finition artisanale',
            ],
            'Céramiste' => [
                'Création céramique',
                'Vaisselle artisanale',
                'Objet décoratif',
                'Émaillage',
                'Pièce sur commande',
                'Sculpture céramique',
                'Cours découverte',
                'Restauration pièce',
                'Décoration céramique',
                'Tournage poterie',
            ],
            'Pâtissier chocolatier' => [
                'Chocolat artisanal',
                'Tablette sur mesure',
                'Coffret chocolat',
                'Dessert chocolat',
                'Pièce événement',
                'Ganache maison',
                'Praliné artisanal',
                'Commande entreprise',
                'Buffet chocolat',
                'Création saisonnière',
            ],
            'Brocanteur' => [
                'Achat antiquités',
                'Vente objets anciens',
                'Estimation meubles',
                'Débarras maison',
                'Recherche pièce rare',
                'Mobilier vintage',
                'Décoration ancienne',
                'Sélection brocante',
                'Conseil antiquités',
                'Objets de collection',
            ],
            'Antiquaire' => [
                'Expertise antiquité',
                'Achat objet ancien',
                'Vente antiquité',
                'Estimation succession',
                'Mobilier ancien',
                'Tableaux anciens',
                'Objets d’art',
                'Restauration conseil',
                'Authentification',
                'Sélection collection',
            ],
        ];
    }
}