<?php

/**
 * Copyright (c) 2026 Auxioma Web Agency
 * https://trouvemoi.eu
 *
 * Ce fichier fait partie du projet Trouvemoi.eu développé par Auxioma Web Agency.
 * Tous droits réservés.
 *
 * Ce code source, son architecture, sa structure, ses scripts et ses composants
 * sont la propriété exclusive de Auxioma Web Agency et de ses partenaires.
 *
 * Toute reproduction, modification, distribution, publication ou utilisation,
 * totale ou partielle, sans autorisation écrite préalable est strictement interdite.
 *
 * Ce code est confidentiel et propriétaire.
 * Droit applicable : Monde.
 */

namespace App\DataFixtures;

use App\Entity\Activity;
use App\Repository\ActivityRepository;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;
use Symfony\Component\String\Slugger\SluggerInterface;

class ActivityFixtures extends Fixture
{
    public const ACTIVITY_MACON = 'activity_macon';
    public const ACTIVITY_ELECTRICIEN = 'activity_electricien';
    public const ACTIVITY_PLOMBIER = 'activity_plombier';

    public function __construct(
        private readonly SluggerInterface $slugger,
        private readonly ActivityRepository $activityRepository,
    ) {
    }

    public function load(ObjectManager $manager): void
    {
        $activities = [
            ['name' => 'Maçon', 'naf' => '43.99C'],
            ['name' => 'Maçon gros œuvre', 'naf' => '43.99C'],
            ['name' => 'Maçon traditionnel', 'naf' => '43.99C'],
            ['name' => 'Maçon du bâti ancien', 'naf' => '43.99C'],
            ['name' => 'Maçon pierre', 'naf' => '43.99C'],
            ['name' => 'Maçon béton armé', 'naf' => '43.99C'],
            ['name' => 'Maçon coffreur', 'naf' => '43.99C'],
            ['name' => 'Coffreur bancheur', 'naf' => '43.99C'],
            ['name' => 'Ferrailleur béton armé', 'naf' => '43.99C'],
            ['name' => 'Boiseur coffreur', 'naf' => '43.99C'],
            ['name' => 'Tailleur de pierre', 'naf' => '43.99C'],
            ['name' => 'Ravaleur maçon', 'naf' => '43.99C'],
            ['name' => 'Rejointoyeur de pierre', 'naf' => '43.99C'],
            ['name' => 'Enduiseur traditionnel', 'naf' => '43.99C'],
            ['name' => 'Constructeur en béton cellulaire', 'naf' => '43.99C'],
            ['name' => 'Monteur de murs porteurs', 'naf' => '43.99C'],
            ['name' => 'Poseur de linteaux', 'naf' => '43.99C'],
            ['name' => 'Poseur de parpaings', 'naf' => '43.99C'],
            ['name' => 'Poseur de briques', 'naf' => '43.99C'],
            ['name' => 'Poseur de blocs béton', 'naf' => '43.99C'],
            ['name' => 'Ouvrier en maçonnerie paysagère', 'naf' => '43.99C'],
            ['name' => 'Maçon VRD', 'naf' => '43.99C'],
            ['name' => 'Maçon en rénovation', 'naf' => '43.99C'],
            ['name' => 'Maçon piscinier', 'naf' => '43.99C'],
            ['name' => 'Chef d\'équipe maçonnerie', 'naf' => '43.99C'],

            ['name' => 'Terrassier', 'naf' => '43.12A'],
            ['name' => 'Terrassier VRD', 'naf' => '43.12A'],
            ['name' => 'Conducteur de pelle', 'naf' => '43.12A'],
            ['name' => 'Conducteur de mini-pelle', 'naf' => '43.12A'],
            ['name' => 'Conducteur de chargeuse', 'naf' => '43.12A'],
            ['name' => 'Conducteur de bulldozer', 'naf' => '43.12A'],
            ['name' => 'Conducteur de tombereau', 'naf' => '43.12A'],
            ['name' => 'Niveleur de terrain', 'naf' => '43.12A'],
            ['name' => 'Poseur de fondations', 'naf' => '43.99C'],
            ['name' => 'Spécialiste fondations profondes', 'naf' => '43.99C'],
            ['name' => 'Foreur de pieux', 'naf' => '43.13Z'],
            ['name' => 'Sondeur géotechnique', 'naf' => '43.13Z'],
            ['name' => 'Démolisseur', 'naf' => '43.11Z'],
            ['name' => 'Curage de bâtiment', 'naf' => '43.11Z'],
            ['name' => 'Scieur béton', 'naf' => '43.11Z'],
            ['name' => 'Carotteur béton', 'naf' => '43.11Z'],
            ['name' => 'Découpeur béton', 'naf' => '43.11Z'],
            ['name' => 'Déconstructeur bâtiment', 'naf' => '43.11Z'],
            ['name' => 'Désamianteur', 'naf' => '39.00Z'],
            ['name' => 'Dépollueur de sols', 'naf' => '39.00Z'],
            ['name' => 'Entreprise de terrassement', 'naf' => '43.12A'],
            ['name' => 'Entreprise de démolition', 'naf' => '43.11Z'],
            ['name' => 'Ouvrier travaux publics bâtiment', 'naf' => '42.11Z'],
            ['name' => 'Manœuvre gros œuvre', 'naf' => '43.99C'],
            ['name' => 'Chef de chantier terrassement', 'naf' => '43.12A'],

            ['name' => 'Charpentier', 'naf' => '43.91A'],
            ['name' => 'Charpentier bois', 'naf' => '43.91A'],
            ['name' => 'Charpentier métallique', 'naf' => '43.91A'],
            ['name' => 'Charpentier traditionnel', 'naf' => '43.91A'],
            ['name' => 'Charpentier industriel', 'naf' => '43.91A'],
            ['name' => 'Monteur de charpente', 'naf' => '43.91A'],
            ['name' => 'Poseur de fermettes', 'naf' => '43.91A'],
            ['name' => 'Constructeur ossature bois', 'naf' => '43.91A'],
            ['name' => 'Monteur ossature bois', 'naf' => '43.91A'],
            ['name' => 'Poseur de poutres', 'naf' => '43.91A'],
            ['name' => 'Poseur de planchers bois', 'naf' => '43.91A'],
            ['name' => 'Restaurateur de charpente ancienne', 'naf' => '43.91A'],
            ['name' => 'Traitement de charpente', 'naf' => '43.91A'],
            ['name' => 'Renforceur de charpente', 'naf' => '43.91A'],
            ['name' => 'Lamellé-collé spécialiste', 'naf' => '43.91A'],
            ['name' => 'Constructeur maison bois', 'naf' => '43.91A'],
            ['name' => 'Constructeur chalet bois', 'naf' => '43.91A'],
            ['name' => 'Bardeur bois', 'naf' => '43.91A'],
            ['name' => 'Bardeur métallique', 'naf' => '43.99B'],
            ['name' => 'Monteur structures métalliques', 'naf' => '43.99B'],
            ['name' => 'Assembleur charpente métallique', 'naf' => '43.99B'],
            ['name' => 'Poseur de connecteurs bois', 'naf' => '43.91A'],
            ['name' => 'Chef d\'équipe charpente', 'naf' => '43.91A'],
            ['name' => 'Technicien charpente', 'naf' => '43.91A'],
            ['name' => 'Entreprise de charpente', 'naf' => '43.91A'],

            ['name' => 'Couvreur', 'naf' => '43.91B'],
            ['name' => 'Couvreur zingueur', 'naf' => '43.91B'],
            ['name' => 'Zingueur', 'naf' => '43.91B'],
            ['name' => 'Ardoisier', 'naf' => '43.91B'],
            ['name' => 'Tuilier', 'naf' => '43.91B'],
            ['name' => 'Poseur de tuiles', 'naf' => '43.91B'],
            ['name' => 'Poseur d\'ardoises', 'naf' => '43.91B'],
            ['name' => 'Poseur de bac acier', 'naf' => '43.91B'],
            ['name' => 'Poseur de toiture zinc', 'naf' => '43.91B'],
            ['name' => 'Poseur de toiture cuivre', 'naf' => '43.91B'],
            ['name' => 'Poseur de gouttières', 'naf' => '43.91B'],
            ['name' => 'Poseur de chéneaux', 'naf' => '43.91B'],
            ['name' => 'Réparateur de toiture', 'naf' => '43.91B'],
            ['name' => 'Dépanneur toiture', 'naf' => '43.91B'],
            ['name' => 'Nettoyeur de toiture', 'naf' => '81.22Z'],
            ['name' => 'Démousseur de toiture', 'naf' => '81.22Z'],
            ['name' => 'Poseur de fenêtre de toit', 'naf' => '43.32A'],
            ['name' => 'Installateur Velux', 'naf' => '43.32A'],
            ['name' => 'Couvreur photovoltaïque', 'naf' => '43.91B'],
            ['name' => 'Étancheur toiture', 'naf' => '43.99A'],
            ['name' => 'Étancheur toit-terrasse', 'naf' => '43.99A'],
            ['name' => 'Poseur membrane EPDM', 'naf' => '43.99A'],
            ['name' => 'Poseur membrane bitume', 'naf' => '43.99A'],
            ['name' => 'Bardeur toiture', 'naf' => '43.91B'],
            ['name' => 'Chef d\'équipe couverture', 'naf' => '43.91B'],

            ['name' => 'Façadier', 'naf' => '43.34Z'],
            ['name' => 'Ravaleur de façade', 'naf' => '43.34Z'],
            ['name' => 'Enduiseur façade', 'naf' => '43.34Z'],
            ['name' => 'Projeteur d\'enduit', 'naf' => '43.34Z'],
            ['name' => 'Iteiste', 'naf' => '43.29A'],
            ['name' => 'Poseur isolation thermique extérieure', 'naf' => '43.29A'],
            ['name' => 'Bardeur façade', 'naf' => '43.99B'],
            ['name' => 'Poseur bardage bois', 'naf' => '43.32A'],
            ['name' => 'Poseur bardage composite', 'naf' => '43.32A'],
            ['name' => 'Poseur bardage métallique', 'naf' => '43.99B'],
            ['name' => 'Peintre façadier', 'naf' => '43.34Z'],
            ['name' => 'Nettoyeur façade', 'naf' => '81.21Z'],
            ['name' => 'Hydrofugeur façade', 'naf' => '43.34Z'],
            ['name' => 'Sableur façade', 'naf' => '43.99D'],
            ['name' => 'Gommeur façade', 'naf' => '43.99D'],
            ['name' => 'Jointoyeur façade', 'naf' => '43.99C'],
            ['name' => 'Restaurateur façade pierre', 'naf' => '43.99C'],
            ['name' => 'Poseur vêture façade', 'naf' => '43.99B'],
            ['name' => 'Technicien fissures façade', 'naf' => '43.99C'],
            ['name' => 'Applicateur crépi', 'naf' => '43.34Z'],
            ['name' => 'Applicateur enduit monocouche', 'naf' => '43.34Z'],
            ['name' => 'Applicateur enduit à la chaux', 'naf' => '43.34Z'],
            ['name' => 'Poseur modénatures façade', 'naf' => '43.99C'],
            ['name' => 'Cordiste façade', 'naf' => '43.99D'],
            ['name' => 'Chef d\'équipe façade', 'naf' => '43.34Z'],

            ['name' => 'Étancheur', 'naf' => '43.99A'],
            ['name' => 'Étancheur bitume', 'naf' => '43.99A'],
            ['name' => 'Étancheur résine', 'naf' => '43.99A'],
            ['name' => 'Étancheur membrane PVC', 'naf' => '43.99A'],
            ['name' => 'Étancheur EPDM', 'naf' => '43.99A'],
            ['name' => 'Étancheur balcon', 'naf' => '43.99A'],
            ['name' => 'Étancheur terrasse', 'naf' => '43.99A'],
            ['name' => 'Étancheur sous-sol', 'naf' => '43.99A'],
            ['name' => 'Applicateur cuvelage', 'naf' => '43.99A'],
            ['name' => 'Applicateur résine d\'étanchéité', 'naf' => '43.99A'],
            ['name' => 'Isolateur thermique', 'naf' => '43.29A'],
            ['name' => 'Isolateur combles', 'naf' => '43.29A'],
            ['name' => 'Isolateur toiture', 'naf' => '43.29A'],
            ['name' => 'Isolateur plancher bas', 'naf' => '43.29A'],
            ['name' => 'Isolateur murs intérieurs', 'naf' => '43.29A'],
            ['name' => 'Souffleur laine de verre', 'naf' => '43.29A'],
            ['name' => 'Souffleur ouate de cellulose', 'naf' => '43.29A'],
            ['name' => 'Calorifugeur', 'naf' => '43.29A'],
            ['name' => 'Poseur pare-vapeur', 'naf' => '43.29A'],
            ['name' => 'Poseur écran sous-toiture', 'naf' => '43.91B'],
            ['name' => 'Technicien étanchéité à l\'air', 'naf' => '43.29A'],
            ['name' => 'Installateur VMC', 'naf' => '43.22B'],
            ['name' => 'Technicien ventilation', 'naf' => '43.22B'],
            ['name' => 'Nettoyeur réseaux VMC', 'naf' => '81.22Z'],
            ['name' => 'Chef d\'équipe isolation', 'naf' => '43.29A'],

            ['name' => 'Menuisier extérieur', 'naf' => '43.32A'],
            ['name' => 'Menuisier bois extérieur', 'naf' => '43.32A'],
            ['name' => 'Menuisier PVC', 'naf' => '43.32A'],
            ['name' => 'Menuisier aluminium', 'naf' => '43.32B'],
            ['name' => 'Poseur de fenêtres', 'naf' => '43.32A'],
            ['name' => 'Poseur de portes d\'entrée', 'naf' => '43.32A'],
            ['name' => 'Poseur de baies vitrées', 'naf' => '43.32A'],
            ['name' => 'Poseur de vérandas', 'naf' => '43.32A'],
            ['name' => 'Vérandaliste', 'naf' => '43.32A'],
            ['name' => 'Poseur de pergolas', 'naf' => '43.32A'],
            ['name' => 'Poseur de volets battants', 'naf' => '43.32A'],
            ['name' => 'Poseur de volets roulants', 'naf' => '43.32A'],
            ['name' => 'Poseur de stores bannes', 'naf' => '43.32A'],
            ['name' => 'Storiste', 'naf' => '43.32A'],
            ['name' => 'Poseur de moustiquaires', 'naf' => '43.32A'],
            ['name' => 'Poseur de garde-corps', 'naf' => '43.32B'],
            ['name' => 'Poseur de portails', 'naf' => '43.29B'],
            ['name' => 'Poseur de portes de garage', 'naf' => '43.29B'],
            ['name' => 'Poseur de clôtures aluminium', 'naf' => '43.29B'],
            ['name' => 'Poseur de brise-soleil', 'naf' => '43.32A'],
            ['name' => 'Installateur brise-vue', 'naf' => '43.29B'],
            ['name' => 'Réparateur menuiseries extérieures', 'naf' => '43.32A'],
            ['name' => 'Dépanneur volet roulant', 'naf' => '43.32A'],
            ['name' => 'Motorisation portail', 'naf' => '43.21A'],
            ['name' => 'Chef d\'équipe menuiserie extérieure', 'naf' => '43.32A'],

            ['name' => 'Menuisier intérieur', 'naf' => '43.32A'],
            ['name' => 'Menuisier agenceur', 'naf' => '43.32A'],
            ['name' => 'Ébéniste agenceur', 'naf' => '31.09B'],
            ['name' => 'Poseur de portes intérieures', 'naf' => '43.32A'],
            ['name' => 'Poseur de placards', 'naf' => '43.32A'],
            ['name' => 'Poseur de dressings', 'naf' => '43.32A'],
            ['name' => 'Poseur d\'escaliers bois', 'naf' => '43.32A'],
            ['name' => 'Escaliéteur', 'naf' => '43.32A'],
            ['name' => 'Poseur de plinthes', 'naf' => '43.32A'],
            ['name' => 'Poseur de moulures', 'naf' => '43.32A'],
            ['name' => 'Poseur de lambris', 'naf' => '43.32A'],
            ['name' => 'Poseur de meubles sur mesure', 'naf' => '43.32A'],
            ['name' => 'Installateur cuisine', 'naf' => '43.32A'],
            ['name' => 'Cuisiniste poseur', 'naf' => '43.32A'],
            ['name' => 'Installateur salle de bain', 'naf' => '43.22A'],
            ['name' => 'Agenceur magasin', 'naf' => '43.32A'],
            ['name' => 'Agenceur bureau', 'naf' => '43.32A'],
            ['name' => 'Poseur de comptoirs', 'naf' => '43.32A'],
            ['name' => 'Poseur de plans de travail', 'naf' => '43.32A'],
            ['name' => 'Monteur mobilier intégré', 'naf' => '43.32A'],
            ['name' => 'Réparateur menuiserie intérieure', 'naf' => '43.32A'],
            ['name' => 'Vernisseur bois', 'naf' => '43.32A'],
            ['name' => 'Laqueur bois', 'naf' => '43.32A'],
            ['name' => 'Restaurateur bois intérieur', 'naf' => '43.32A'],
            ['name' => 'Chef d\'équipe agencement', 'naf' => '43.32A'],

            ['name' => 'Serrurier', 'naf' => '43.32B'],
            ['name' => 'Serrurier dépanneur', 'naf' => '43.32B'],
            ['name' => 'Serrurier métallier', 'naf' => '43.32B'],
            ['name' => 'Métallier', 'naf' => '25.99B'],
            ['name' => 'Ferronnier', 'naf' => '25.99B'],
            ['name' => 'Chaudronnier bâtiment', 'naf' => '25.99B'],
            ['name' => 'Soudeur bâtiment', 'naf' => '25.62B'],
            ['name' => 'Poseur de serrures', 'naf' => '43.32B'],
            ['name' => 'Poseur de portes blindées', 'naf' => '43.32B'],
            ['name' => 'Poseur de rideaux métalliques', 'naf' => '43.32B'],
            ['name' => 'Poseur de grilles métalliques', 'naf' => '43.32B'],
            ['name' => 'Poseur de garde-corps métal', 'naf' => '43.32B'],
            ['name' => 'Poseur d\'escaliers métal', 'naf' => '43.32B'],
            ['name' => 'Poseur de verrières', 'naf' => '43.32B'],
            ['name' => 'Poseur de cloisons vitrées', 'naf' => '43.32B'],
            ['name' => 'Vitrier', 'naf' => '43.34Z'],
            ['name' => 'Miroitier', 'naf' => '43.34Z'],
            ['name' => 'Poseur de double vitrage', 'naf' => '43.34Z'],
            ['name' => 'Réparateur vitrage', 'naf' => '43.34Z'],
            ['name' => 'Poseur miroirs', 'naf' => '43.34Z'],
            ['name' => 'Poseur vitrines magasin', 'naf' => '43.34Z'],
            ['name' => 'Installateur contrôle d\'accès', 'naf' => '43.21A'],
            ['name' => 'Motorisation rideau métallique', 'naf' => '43.21A'],
            ['name' => 'Technicien fermeture bâtiment', 'naf' => '43.32B'],
            ['name' => 'Chef d\'équipe serrurerie', 'naf' => '43.32B'],

            ['name' => 'Plombier', 'naf' => '43.22A'],
            ['name' => 'Plombier sanitaire', 'naf' => '43.22A'],
            ['name' => 'Plombier dépanneur', 'naf' => '43.22A'],
            ['name' => 'Installateur sanitaire', 'naf' => '43.22A'],
            ['name' => 'Poseur de robinetterie', 'naf' => '43.22A'],
            ['name' => 'Poseur de WC', 'naf' => '43.22A'],
            ['name' => 'Poseur de douche', 'naf' => '43.22A'],
            ['name' => 'Poseur de baignoire', 'naf' => '43.22A'],
            ['name' => 'Poseur de receveur', 'naf' => '43.22A'],
            ['name' => 'Poseur de lavabo', 'naf' => '43.22A'],
            ['name' => 'Installateur salle d\'eau', 'naf' => '43.22A'],
            ['name' => 'Réparateur fuite d\'eau', 'naf' => '43.22A'],
            ['name' => 'Déboucheur canalisation', 'naf' => '43.22A'],
            ['name' => 'Hydrocureur', 'naf' => '43.22A'],
            ['name' => 'Caméra inspection canalisation', 'naf' => '43.22A'],
            ['name' => 'Poseur adoucisseur d\'eau', 'naf' => '43.22A'],
            ['name' => 'Poseur chauffe-eau électrique', 'naf' => '43.22A'],
            ['name' => 'Poseur ballon thermodynamique', 'naf' => '43.22A'],
            ['name' => 'Poseur réseaux PER', 'naf' => '43.22A'],
            ['name' => 'Poseur réseaux cuivre', 'naf' => '43.22A'],
            ['name' => 'Poseur réseaux multicouche', 'naf' => '43.22A'],
            ['name' => 'Poseur évacuation PVC', 'naf' => '43.22A'],
            ['name' => 'Installateur surpresseur', 'naf' => '43.22A'],
            ['name' => 'Technicien traitement de l\'eau', 'naf' => '43.22A'],
            ['name' => 'Chef d\'équipe plomberie', 'naf' => '43.22A'],

            ['name' => 'Chauffagiste', 'naf' => '43.22B'],
            ['name' => 'Technicien chauffage', 'naf' => '43.22B'],
            ['name' => 'Installateur chaudière gaz', 'naf' => '43.22B'],
            ['name' => 'Installateur chaudière fioul', 'naf' => '43.22B'],
            ['name' => 'Installateur chaudière bois', 'naf' => '43.22B'],
            ['name' => 'Installateur poêle à bois', 'naf' => '43.22B'],
            ['name' => 'Installateur poêle à granulés', 'naf' => '43.22B'],
            ['name' => 'Fumiste', 'naf' => '43.22B'],
            ['name' => 'Ramoneur', 'naf' => '81.22Z'],
            ['name' => 'Installateur radiateurs', 'naf' => '43.22B'],
            ['name' => 'Installateur plancher chauffant', 'naf' => '43.22B'],
            ['name' => 'Installateur pompe à chaleur', 'naf' => '43.22B'],
            ['name' => 'Technicien pompe à chaleur', 'naf' => '43.22B'],
            ['name' => 'Climaticien', 'naf' => '43.22B'],
            ['name' => 'Installateur climatisation', 'naf' => '43.22B'],
            ['name' => 'Frigoriste', 'naf' => '43.22B'],
            ['name' => 'Technicien froid', 'naf' => '43.22B'],
            ['name' => 'Installateur ventilation double flux', 'naf' => '43.22B'],
            ['name' => 'Technicien maintenance chaudière', 'naf' => '43.22B'],
            ['name' => 'Technicien maintenance climatisation', 'naf' => '43.22B'],
            ['name' => 'Installateur réseau gaz', 'naf' => '43.22B'],
            ['name' => 'Tuyauteur chauffage', 'naf' => '43.22B'],
            ['name' => 'Calorifugeur réseau chauffage', 'naf' => '43.22B'],
            ['name' => 'Metteur au point CVC', 'naf' => '43.22B'],
            ['name' => 'Chef d\'équipe CVC', 'naf' => '43.22B'],

            ['name' => 'Électricien', 'naf' => '43.21A'],
            ['name' => 'Électricien bâtiment', 'naf' => '43.21A'],
            ['name' => 'Électricien rénovation', 'naf' => '43.21A'],
            ['name' => 'Électricien neuf', 'naf' => '43.21A'],
            ['name' => 'Électricien dépanneur', 'naf' => '43.21A'],
            ['name' => 'Tableautier électrique', 'naf' => '43.21A'],
            ['name' => 'Poseur tableau électrique', 'naf' => '43.21A'],
            ['name' => 'Poseur disjoncteur', 'naf' => '43.21A'],
            ['name' => 'Installateur prise électrique', 'naf' => '43.21A'],
            ['name' => 'Installateur éclairage intérieur', 'naf' => '43.21A'],
            ['name' => 'Installateur éclairage extérieur', 'naf' => '43.21A'],
            ['name' => 'Poseur borne recharge électrique', 'naf' => '43.21A'],
            ['name' => 'Installateur chauffage électrique', 'naf' => '43.21A'],
            ['name' => 'Installateur plancher chauffant électrique', 'naf' => '43.21A'],
            ['name' => 'Technicien mise aux normes électriques', 'naf' => '43.21A'],
            ['name' => 'Électricien tertiaire', 'naf' => '43.21A'],
            ['name' => 'Électricien industriel bâtiment', 'naf' => '43.21A'],
            ['name' => 'Câbleur bâtiment', 'naf' => '43.21A'],
            ['name' => 'Tireur de câbles', 'naf' => '43.21A'],
            ['name' => 'Poseur chemin de câble', 'naf' => '43.21A'],
            ['name' => 'Technicien compteur électrique', 'naf' => '43.21A'],
            ['name' => 'Installateur groupe électrogène', 'naf' => '43.21A'],
            ['name' => 'Installateur parafoudre', 'naf' => '43.21A'],
            ['name' => 'Diagnostiqueur installation électrique', 'naf' => '43.21A'],
            ['name' => 'Chef d\'équipe électricité', 'naf' => '43.21A'],
            ['name' => 'Domoticien', 'naf' => '43.21A'],
            ['name' => 'Intégrateur domotique', 'naf' => '43.21A'],
            ['name' => 'Installateur alarme', 'naf' => '43.21A'],
            ['name' => 'Installateur vidéosurveillance', 'naf' => '43.21A'],
            ['name' => 'Installateur interphone', 'naf' => '43.21A'],
            ['name' => 'Installateur visiophone', 'naf' => '43.21A'],
            ['name' => 'Installateur contrôle d\'accès', 'naf' => '43.21A'],
            ['name' => 'Installateur réseau informatique', 'naf' => '43.21A'],
            ['name' => 'Câbleur RJ45', 'naf' => '43.21A'],
            ['name' => 'Technicien fibre optique', 'naf' => '42.22Z'],
            ['name' => 'Installateur antenne TV', 'naf' => '43.21A'],
            ['name' => 'Installateur parabole', 'naf' => '43.21A'],
            ['name' => 'Installateur sonorisation bâtiment', 'naf' => '43.21A'],
            ['name' => 'Installateur Wi-Fi professionnel', 'naf' => '43.21A'],
            ['name' => 'Installateur objets connectés maison', 'naf' => '43.21A'],
            ['name' => 'Technicien GTB', 'naf' => '43.21A'],
            ['name' => 'Technicien GTC', 'naf' => '43.21A'],
            ['name' => 'Automaticien bâtiment', 'naf' => '43.21A'],
            ['name' => 'Installateur portail automatique', 'naf' => '43.21A'],
            ['name' => 'Installateur volets connectés', 'naf' => '43.21A'],
            ['name' => 'Technicien sécurité incendie', 'naf' => '43.21A'],
            ['name' => 'Installateur détecteurs fumée', 'naf' => '43.21A'],
            ['name' => 'Installateur éclairage connecté', 'naf' => '43.21A'],
            ['name' => 'Installateur serrure connectée', 'naf' => '43.21A'],
            ['name' => 'Chef d\'équipe courant faible', 'naf' => '43.21A'],
            ['name' => 'Installateur panneaux solaires', 'naf' => '43.21A'],
            ['name' => 'Installateur photovoltaïque', 'naf' => '43.21A'],
            ['name' => 'Installateur solaire thermique', 'naf' => '43.22B'],
            ['name' => 'Technicien maintenance photovoltaïque', 'naf' => '43.21A'],
            ['name' => 'Poseur onduleur solaire', 'naf' => '43.21A'],
            ['name' => 'Poseur batterie solaire', 'naf' => '43.21A'],
            ['name' => 'Installateur chauffe-eau solaire', 'naf' => '43.22B'],
            ['name' => 'Installateur autoconsommation', 'naf' => '43.21A'],
            ['name' => 'Installateur ombrière solaire', 'naf' => '43.21A'],
            ['name' => 'Installateur carport solaire', 'naf' => '43.21A'],
            ['name' => 'Technicien raccordement solaire', 'naf' => '43.21A'],
            ['name' => 'Installateur pompe à chaleur air-eau', 'naf' => '43.22B'],
            ['name' => 'Installateur pompe à chaleur air-air', 'naf' => '43.22B'],
            ['name' => 'Installateur géothermie', 'naf' => '43.22B'],
            ['name' => 'Technicien géothermie', 'naf' => '43.22B'],
            ['name' => 'Installateur chaudière biomasse', 'naf' => '43.22B'],
            ['name' => 'Installateur poêle granulés', 'naf' => '43.22B'],
            ['name' => 'Installateur récupération eaux de pluie', 'naf' => '43.22A'],
            ['name' => 'Installateur ventilation basse consommation', 'naf' => '43.22B'],
            ['name' => 'Conseiller rénovation énergétique', 'naf' => '74.90B'],
            ['name' => 'Auditeur énergétique', 'naf' => '71.20B'],
            ['name' => 'Technicien isolation énergétique', 'naf' => '43.29A'],
            ['name' => 'Technicien rénovation globale', 'naf' => '43.39Z'],
            ['name' => 'Accompagnateur rénovation énergétique', 'naf' => '74.90B'],
            ['name' => 'Chef de projet énergie bâtiment', 'naf' => '71.12B'],

            ['name' => 'Plaquiste', 'naf' => '43.31Z'],
            ['name' => 'Plâtrier', 'naf' => '43.31Z'],
            ['name' => 'Plâtrier plaquiste', 'naf' => '43.31Z'],
            ['name' => 'Jointoyeur placo', 'naf' => '43.31Z'],
            ['name' => 'Bandiste', 'naf' => '43.31Z'],
            ['name' => 'Poseur plaques de plâtre', 'naf' => '43.31Z'],
            ['name' => 'Poseur cloisons sèches', 'naf' => '43.31Z'],
            ['name' => 'Poseur cloisons modulaires', 'naf' => '43.31Z'],
            ['name' => 'Poseur cloisons amovibles', 'naf' => '43.31Z'],
            ['name' => 'Poseur doublage isolant', 'naf' => '43.31Z'],
            ['name' => 'Poseur faux plafond', 'naf' => '43.31Z'],
            ['name' => 'Poseur plafond suspendu', 'naf' => '43.31Z'],
            ['name' => 'Poseur plafond acoustique', 'naf' => '43.31Z'],
            ['name' => 'Staffeur', 'naf' => '43.31Z'],
            ['name' => 'Stucateur', 'naf' => '43.31Z'],
            ['name' => 'Ornemaniste plâtre', 'naf' => '43.31Z'],
            ['name' => 'Poseur corniches', 'naf' => '43.31Z'],
            ['name' => 'Poseur rosaces plafond', 'naf' => '43.31Z'],
            ['name' => 'Poseur trappes de visite', 'naf' => '43.31Z'],
            ['name' => 'Poseur carreaux de plâtre', 'naf' => '43.31Z'],
            ['name' => 'Poseur cloison hydrofuge', 'naf' => '43.31Z'],
            ['name' => 'Poseur cloison coupe-feu', 'naf' => '43.31Z'],
            ['name' => 'Technicien isolation acoustique', 'naf' => '43.31Z'],
            ['name' => 'Correcteur acoustique intérieur', 'naf' => '43.31Z'],
            ['name' => 'Chef d\'équipe plâtrerie', 'naf' => '43.31Z'],

            ['name' => 'Peintre en bâtiment', 'naf' => '43.34Z'],
            ['name' => 'Peintre intérieur', 'naf' => '43.34Z'],
            ['name' => 'Peintre extérieur', 'naf' => '43.34Z'],
            ['name' => 'Peintre décorateur', 'naf' => '43.34Z'],
            ['name' => 'Peintre façadier', 'naf' => '43.34Z'],
            ['name' => 'Enduiseur intérieur', 'naf' => '43.34Z'],
            ['name' => 'Ratissage murs', 'naf' => '43.34Z'],
            ['name' => 'Poseur toile de verre', 'naf' => '43.34Z'],
            ['name' => 'Poseur papier peint', 'naf' => '43.34Z'],
            ['name' => 'Tapissier mural', 'naf' => '43.34Z'],
            ['name' => 'Décorateur intérieur', 'naf' => '74.10Z'],
            ['name' => 'Coloriste bâtiment', 'naf' => '43.34Z'],
            ['name' => 'Applicateur béton ciré', 'naf' => '43.33Z'],
            ['name' => 'Applicateur enduit décoratif', 'naf' => '43.34Z'],
            ['name' => 'Applicateur stuc', 'naf' => '43.34Z'],
            ['name' => 'Applicateur tadelakt', 'naf' => '43.34Z'],
            ['name' => 'Applicateur peinture écologique', 'naf' => '43.34Z'],
            ['name' => 'Vernisseur bâtiment', 'naf' => '43.34Z'],
            ['name' => 'Laqueur bâtiment', 'naf' => '43.34Z'],
            ['name' => 'Peintre sol résine', 'naf' => '43.34Z'],
            ['name' => 'Peintre anti-humidité', 'naf' => '43.34Z'],
            ['name' => 'Peintre après sinistre', 'naf' => '43.34Z'],
            ['name' => 'Restaurateur peinture ancienne', 'naf' => '43.34Z'],
            ['name' => 'Nettoyeur murs plafonds', 'naf' => '81.21Z'],
            ['name' => 'Chef d\'équipe peinture', 'naf' => '43.34Z'],

            ['name' => 'Carreleur', 'naf' => '43.33Z'],
            ['name' => 'Mosaïste', 'naf' => '43.33Z'],
            ['name' => 'Poseur faïence', 'naf' => '43.33Z'],
            ['name' => 'Poseur carrelage grand format', 'naf' => '43.33Z'],
            ['name' => 'Poseur carrelage extérieur', 'naf' => '43.33Z'],
            ['name' => 'Poseur pierre naturelle', 'naf' => '43.33Z'],
            ['name' => 'Marbrier bâtiment', 'naf' => '43.99C'],
            ['name' => 'Poseur marbre', 'naf' => '43.33Z'],
            ['name' => 'Poseur travertin', 'naf' => '43.33Z'],
            ['name' => 'Poseur parquet', 'naf' => '43.33Z'],
            ['name' => 'Parqueteur', 'naf' => '43.33Z'],
            ['name' => 'Ponceur parquet', 'naf' => '43.33Z'],
            ['name' => 'Vitrificateur parquet', 'naf' => '43.33Z'],
            ['name' => 'Poseur stratifié', 'naf' => '43.33Z'],
            ['name' => 'Poseur sol vinyle', 'naf' => '43.33Z'],
            ['name' => 'Poseur sol PVC', 'naf' => '43.33Z'],
            ['name' => 'Poseur linoléum', 'naf' => '43.33Z'],
            ['name' => 'Solier moquettiste', 'naf' => '43.33Z'],
            ['name' => 'Poseur moquette', 'naf' => '43.33Z'],
            ['name' => 'Poseur sol textile', 'naf' => '43.33Z'],
            ['name' => 'Poseur résine sol', 'naf' => '43.33Z'],
            ['name' => 'Applicateur sol industriel', 'naf' => '43.33Z'],
            ['name' => 'Poseur dalle sur plots', 'naf' => '43.33Z'],
            ['name' => 'Poseur terrasse carrelée', 'naf' => '43.33Z'],
            ['name' => 'Chef d\'équipe revêtements', 'naf' => '43.33Z'],

            ['name' => 'Paysagiste', 'naf' => '81.30Z'],
            ['name' => 'Jardinier paysagiste', 'naf' => '81.30Z'],
            ['name' => 'Maçon paysager', 'naf' => '43.99C'],
            ['name' => 'Poseur terrasse bois', 'naf' => '43.32A'],
            ['name' => 'Poseur terrasse composite', 'naf' => '43.32A'],
            ['name' => 'Poseur terrasse pierre', 'naf' => '43.33Z'],
            ['name' => 'Poseur pavés', 'naf' => '43.99C'],
            ['name' => 'Poseur dallage extérieur', 'naf' => '43.99C'],
            ['name' => 'Poseur bordures', 'naf' => '42.11Z'],
            ['name' => 'Poseur clôtures', 'naf' => '43.29B'],
            ['name' => 'Poseur grillage', 'naf' => '43.29B'],
            ['name' => 'Poseur portail extérieur', 'naf' => '43.29B'],
            ['name' => 'Piscinier', 'naf' => '43.99C'],
            ['name' => 'Constructeur piscine béton', 'naf' => '43.99C'],
            ['name' => 'Poseur coque piscine', 'naf' => '43.99C'],
            ['name' => 'Technicien piscine', 'naf' => '43.22B'],
            ['name' => 'Poseur arrosage automatique', 'naf' => '43.22A'],
            ['name' => 'Poseur drainage terrain', 'naf' => '43.12A'],
            ['name' => 'Poseur caniveaux', 'naf' => '42.11Z'],
            ['name' => 'Poseur réseaux VRD', 'naf' => '42.11Z'],
            ['name' => 'Poseur regard eaux pluviales', 'naf' => '42.21Z'],
            ['name' => 'Poseur assainissement individuel', 'naf' => '37.00Z'],
            ['name' => 'Installateur fosse septique', 'naf' => '37.00Z'],
            ['name' => 'Poseur micro-station', 'naf' => '37.00Z'],
            ['name' => 'Chef d\'équipe aménagement extérieur', 'naf' => '81.30Z'],

            ['name' => 'Architecte', 'naf' => '71.11Z'],
            ['name' => 'Architecte d\'intérieur', 'naf' => '74.10Z'],
            ['name' => 'Maître d\'œuvre', 'naf' => '71.11Z'],
            ['name' => 'Conducteur de travaux', 'naf' => '43.99C'],
            ['name' => 'Chef de chantier', 'naf' => '43.99C'],
            ['name' => 'Coordinateur travaux', 'naf' => '43.99C'],
            ['name' => 'Économiste de la construction', 'naf' => '74.90A'],
            ['name' => 'Métreur bâtiment', 'naf' => '74.90A'],
            ['name' => 'Deviseur bâtiment', 'naf' => '74.90A'],
            ['name' => 'Dessinateur bâtiment', 'naf' => '71.12B'],
            ['name' => 'Dessinateur projeteur', 'naf' => '71.12B'],
            ['name' => 'BIM modeleur', 'naf' => '71.12B'],
            ['name' => 'BIM coordinateur', 'naf' => '71.12B'],
            ['name' => 'Ingénieur structure', 'naf' => '71.12B'],
            ['name' => 'Bureau d\'études structure', 'naf' => '71.12B'],
            ['name' => 'Bureau d\'études thermique', 'naf' => '71.12B'],
            ['name' => 'Bureau d\'études fluides', 'naf' => '71.12B'],
            ['name' => 'Bureau d\'études électricité', 'naf' => '71.12B'],
            ['name' => 'Thermicien', 'naf' => '71.12B'],
            ['name' => 'Acousticien bâtiment', 'naf' => '71.12B'],
            ['name' => 'Géomètre-topographe', 'naf' => '71.12A'],
            ['name' => 'Diagnostiqueur immobilier', 'naf' => '71.20B'],
            ['name' => 'Coordinateur SPS', 'naf' => '74.90B'],
            ['name' => 'OPC chantier', 'naf' => '74.90B'],
            ['name' => 'Assistant maîtrise d\'ouvrage', 'naf' => '74.90B'],
            ['name' => 'Agent de maintenance bâtiment', 'naf' => '81.10Z'],
            ['name' => 'Technicien multitechnique', 'naf' => '81.10Z'],
            ['name' => 'Technicien multiservices', 'naf' => '81.10Z'],
            ['name' => 'Homme toutes mains bâtiment', 'naf' => '81.10Z'],
            ['name' => 'Dépanneur bâtiment', 'naf' => '81.10Z'],
            ['name' => 'Réparateur après sinistre', 'naf' => '81.10Z'],
            ['name' => 'Assécheur après dégât des eaux', 'naf' => '81.10Z'],
            ['name' => 'Décontaminateur après incendie', 'naf' => '39.00Z'],
            ['name' => 'Nettoyeur fin de chantier', 'naf' => '81.21Z'],
            ['name' => 'Nettoyeur après travaux', 'naf' => '81.21Z'],
            ['name' => 'Nettoyeur façade', 'naf' => '81.21Z'],
            ['name' => 'Nettoyeur toiture', 'naf' => '81.22Z'],
            ['name' => 'Nettoyeur vitres bâtiment', 'naf' => '81.22Z'],
            ['name' => 'Cordiste bâtiment', 'naf' => '43.99D'],
            ['name' => 'Nacelliste', 'naf' => '43.99D'],
            ['name' => 'Échafaudeur', 'naf' => '43.99D'],
            ['name' => 'Monteur échafaudage', 'naf' => '43.99D'],
            ['name' => 'Poseur protections chantier', 'naf' => '43.99D'],
            ['name' => 'Installateur base vie chantier', 'naf' => '43.99D'],
            ['name' => 'Magasinier chantier', 'naf' => '52.10B'],
            ['name' => 'Loueur matériel avec opérateur', 'naf' => '77.32Z'],
            ['name' => 'Technicien désenfumage', 'naf' => '43.22B'],
            ['name' => 'Mainteneur portes automatiques', 'naf' => '43.29B'],
            ['name' => 'Mainteneur ascenseur', 'naf' => '43.29B'],
            ['name' => 'Chef d\'équipe maintenance bâtiment', 'naf' => '81.10Z'],
            ['name' => 'Monteur échafaudage roulant', 'naf' => '43.99D'],
            ['name' => 'Monteur échafaudage fixe', 'naf' => '43.99D'],
            ['name' => 'Cordiste industriel', 'naf' => '43.99D'],
            ['name' => 'Technicien accès difficile', 'naf' => '43.99D'],
            ['name' => 'Installateur ligne de vie', 'naf' => '43.99D'],
            ['name' => 'Poseur garde-corps toiture', 'naf' => '43.99D'],
            ['name' => 'Poseur filets de sécurité', 'naf' => '43.99D'],
            ['name' => 'Technicien sécurité chantier', 'naf' => '74.90B'],
            ['name' => 'Coordinateur sécurité chantier', 'naf' => '74.90B'],
            ['name' => 'Contrôleur conformité chantier', 'naf' => '71.20B'],
            ['name' => 'Inspecteur bâtiment', 'naf' => '71.20B'],
            ['name' => 'Expert bâtiment', 'naf' => '71.20B'],
            ['name' => 'Expert fissures maison', 'naf' => '71.20B'],
            ['name' => 'Expert humidité bâtiment', 'naf' => '71.20B'],
            ['name' => 'Expert infiltration toiture', 'naf' => '71.20B'],
            ['name' => 'Technicien humidité', 'naf' => '71.20B'],
            ['name' => 'Technicien mérule', 'naf' => '39.00Z'],
            ['name' => 'Traitement bois charpente', 'naf' => '43.91A'],
            ['name' => 'Traitement termites', 'naf' => '81.29A'],
            ['name' => 'Traitement nuisibles bâtiment', 'naf' => '81.29A'],
            ['name' => 'Dératiseur bâtiment', 'naf' => '81.29A'],
            ['name' => 'Désinsectiseur bâtiment', 'naf' => '81.29A'],
            ['name' => 'Technicien anti-pigeons', 'naf' => '81.29A'],
            ['name' => 'Installateur pics anti-pigeons', 'naf' => '81.29A'],
            ['name' => 'Installateur filets anti-volatiles', 'naf' => '81.29A'],

            ['name' => 'Constructeur maison individuelle', 'naf' => '41.20A'],
            ['name' => 'Constructeur extension maison', 'naf' => '41.20A'],
            ['name' => 'Constructeur surélévation maison', 'naf' => '41.20A'],
            ['name' => 'Constructeur bâtiment agricole', 'naf' => '41.20B'],
            ['name' => 'Constructeur bâtiment industriel', 'naf' => '41.20B'],
            ['name' => 'Constructeur hangar métallique', 'naf' => '41.20B'],
            ['name' => 'Monteur bâtiment modulaire', 'naf' => '41.20B'],
            ['name' => 'Installateur bungalow chantier', 'naf' => '43.99D'],
            ['name' => 'Monteur containers aménagés', 'naf' => '41.20B'],
            ['name' => 'Constructeur tiny house', 'naf' => '41.20A'],
            ['name' => 'Constructeur studio de jardin', 'naf' => '41.20A'],
            ['name' => 'Poseur abri de jardin', 'naf' => '43.32A'],
            ['name' => 'Constructeur garage préfabriqué', 'naf' => '41.20A'],
            ['name' => 'Poseur carport', 'naf' => '43.32A'],
            ['name' => 'Poseur pergola bioclimatique', 'naf' => '43.32A'],
            ['name' => 'Poseur véranda aluminium', 'naf' => '43.32A'],
            ['name' => 'Poseur véranda bois', 'naf' => '43.32A'],
            ['name' => 'Poseur sas d\'entrée', 'naf' => '43.32A'],
            ['name' => 'Installateur fermeture industrielle', 'naf' => '43.29B'],
            ['name' => 'Poseur quai de chargement', 'naf' => '43.29B'],
            ['name' => 'Installateur porte sectionnelle', 'naf' => '43.29B'],
            ['name' => 'Installateur rideau rapide', 'naf' => '43.29B'],
            ['name' => 'Technicien portes industrielles', 'naf' => '43.29B'],
            ['name' => 'Monteur rayonnage industriel', 'naf' => '43.99B'],
            ['name' => 'Installateur mezzanine industrielle', 'naf' => '43.99B'],
            ['name' => 'Poseur résine étanchéité parking', 'naf' => '43.99A'],
            ['name' => 'Applicateur peinture parking', 'naf' => '43.34Z'],
            ['name' => 'Traceur marquage au sol', 'naf' => '42.11Z'],
            ['name' => 'Poseur signalisation parking', 'naf' => '42.11Z'],
            ['name' => 'Installateur borne parking', 'naf' => '43.21A'],
            ['name' => 'Poseur ralentisseurs', 'naf' => '42.11Z'],
            ['name' => 'Poseur mobilier urbain', 'naf' => '43.99C'],
            ['name' => 'Installateur abribus', 'naf' => '43.99C'],
            ['name' => 'Poseur panneaux urbains', 'naf' => '43.99C'],
            ['name' => 'Poseur glissières sécurité', 'naf' => '42.11Z'],
            ['name' => 'Technicien voirie', 'naf' => '42.11Z'],
            ['name' => 'Technicien éclairage public', 'naf' => '43.21A'],
            ['name' => 'Installateur feux tricolores', 'naf' => '43.21A'],
            ['name' => 'Poseur réseaux enterrés', 'naf' => '42.22Z'],
            ['name' => 'Terrassier réseaux secs', 'naf' => '42.22Z'],
            ['name' => 'Terrassier réseaux humides', 'naf' => '42.21Z'],
            ['name' => 'Poseur fibre enterrée', 'naf' => '42.22Z'],
            ['name' => 'Technicien eau potable', 'naf' => '42.21Z'],
            ['name' => 'Technicien assainissement', 'naf' => '37.00Z'],
            ['name' => 'Poseur station relevage', 'naf' => '37.00Z'],
            ['name' => 'Installateur récupération eaux grises', 'naf' => '37.00Z'],
            ['name' => 'Technicien forage eau', 'naf' => '43.13Z'],
            ['name' => 'Foreur puits', 'naf' => '43.13Z'],
            ['name' => 'Installateur pompe immergée', 'naf' => '43.22A'],
            ['name' => 'Technicien hydraulique bâtiment', 'naf' => '43.22A'],
        ];

        foreach ($activities as $data) {
            $slug = $this->slugger
                ->slug($data['name'])
                ->lower()
                ->toString();

            $reference = 'activity_' . $slug;

            $existingActivity = $this->activityRepository->findOneBy([
                'name' => $data['name'],
            ]);

            if ($existingActivity) {
                $this->setReference($reference, $existingActivity);
                continue;
            }

            $activity = new Activity();
            $activity->setName($data['name']);
            $activity->setNaf($data['naf']);
            $activity->setSlug($slug);

            $manager->persist($activity);
            $this->setReference($reference, $activity);
        }

        $manager->flush();
    }
}
